# Generated by Django 3.0.3 on 2020-03-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('repeat', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='user_settings',
            old_name='filter_pump_state',
            new_name='pump_state',
        ),
    ]
